# ou are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.


"""
Approach 1: Using a Hashmap (Counter) 

let s = len(s) and t = len(t)

TC: O(s + t)
SC: O(t)
"""

from collections import Counter

def findTheDifference(self, s: str, t: str) -> str:
    t_counter = Counter(t)

    for char in s:
        if char in t_counter:
            t_counter[char] -= 1

    for char in t_counter:
        if t_counter[char] == 1:
            return char

"""
Approach 2: Using XOR (Constant Space)

TC: O(s + t)
SC: O(1)
"""

def findTheDifference(self, s: str, t: str) -> str:

    xor = 0

    for ch in t:
        xor = xor ^ ord(ch)

    for ch in s:
        xor = xor ^ ord(ch)

    return chr(xor)

